server:
  port: 8092
  servlet:
    context-path: /infovision
    
spring:
  application:
    name: infovision-canteen-service
  profiles:
    active: local
    
#    
    
################ Paytm Properties #########################
#paytm.payment.sandbox.merchantId:OhdWxs28091023394981
#paytm.payment.sandbox.merchantKey:nLJjON#9M_rcXlw2
#paytm.payment.sandbox.channelId:WEB
#paytm.payment.sandbox.industryTypeId:Retail
#paytm.payment.sandbox.website:WEBSTAGING
#paytm.payment.sandbox.paytmUrl:https://securegw-stage.paytm.in/order/process
#paytm.payment.sandbox.callbackUrl:http://localhost:8080/pgresponse
#paytm.payment.sandbox.details.MID: ${paytm.payment.sandbox.merchantId} 
#paytm.payment.sandbox.details.CHANNEL_ID: ${paytm.payment.sandbox.channelId}
#paytm.payment.sandbox.details.INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industryTypeId}
#paytm.payment.sandbox.details.WEBSITE: ${paytm.payment.sandbox.website}
#paytm.payment.sandbox.details.CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}
#paytm.mobile = 9133086749
#paytm.email = rajendrakatikala04@gmail.com
  
#  servlet:
#    context-path: /infovision
#    
#spring:
#  application:
#    name: infovision-canteen-service
#  profiles:
#    active: local
